apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: argo-deployment-pod
spec: 
  selector: 
    matchLabels: 
      app: myapp 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: myapp 
    spec: 
      containers: 
      - name: demo-cont 
        image: teaimg
        imagePullPolicy: Never 
        args:
        - /bin/sh
        - -c
        - touch argo; sleep 25; rm -f argo; sleep 500
      livenessProbe:
        exec:
          command:
            - cat
            - argo
        initialDelaySeconds: 5
        periodSeconds: 5
