apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: argo-ingress-deployment-pod
spec: 
  selector: 
    matchLabels: 
      app: myapp 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: myapp 
    spec: 
      containers: 
      - name: demo-cont 
        image: teaimg 
        imagePullPolicy: Never 
