apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapplication
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Iam-jayabharathi/argocd.git
    path: kubernetes/
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: nginx
          tag: latest
