namespace: default  

replicas: 1
version: v1

new:
  image: myimg
  pullPolicy: Never
  tag: d0b4a43a1180

new2:  
  image2: teaimg
  pullPolicy: Never
  tag: d0b4a43a1189

app: node
tea: node

strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 0

service:
  port: 80
  targetport: 3000

restartPolicy: Always
secretname: aximdemosecret-tls
hostname: noc.aximsoft.com
