name: argocd
on:
  push:
    branches: [ master ]
jobs:
  argocd:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Build the Docker image 
      uses: actions/checkout@v1 
      with: 
        repository: iam-jayabharathi/argocd 
        token: ${{ secrets.MYGIT_TOKEN }} 
        path: demochart
        ref: master
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: argocd-test
        IMAGE_TAG: ${{ github.sha }}  
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        cd /home/aximsoft/aximsoft/minikube/actions-runner/_work/argocd/demochart
        git config --global user.email "jayabharathissy@gmail.com"
        git config --global user.name "Iam-jayabharathi"
        TAG=$(cat ./demochart/values.yaml |  grep tag: | awk '{print $2}')
        sed -i 's/$TAG/$IMAGE_TAG/' ./demochart/values.yaml
        git add ./demochart/values.yaml
        git commit -m "Docker image tag updated for noc.aximsoft.com - $IMAGE_TAG "
        
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MYGIT_TOKEN }}
        repository: iam-jayabharathi/argocd 
        branch: master
        directory: /home/aximsoft/aximsoft/minikube/actions-runner/_work/argocd
